### ISSUE TITLE
Modifying Header & Favicon

### ISSUE THREAD

**Issue by 2024-SANDHYA** [geekymeeky/JS-games#19]
The header is way too bland , so will modify that & will also add a footer at the bottom of the website. Adding Favicon also.

**Comment by geekymeeky** [comment]
An issue for the footer is already present and has been assigned #15 . You can go for the header and favicon :smiley: .

**Comment by 2024-SANDHYA** [comment]
> 
> 
> An issue for the footer is already present and has been assigned #15 . You can go for the header and favicon 😃 .

Thank you !! :-)

**Comment by geekymeeky** [comment]
Closed via #101
