### ISSUE TITLE
Organize files

### ISSUE THREAD

**Issue by geekymeeky** [geekymeeky/JS-games#3]
### Aim
- Organize all the files
### Details
- Put all CSS files in ` static/css/ `
- Put all JS files in ` static/js/ `
- Link the new paths to the frontend

**Comment by madihamallick** [comment]
@geekymeeky please assign this to me.

**Comment by geekymeeky** [comment]
@madihamallick assigned to you.

**Comment by geekymeeky** [comment]
Closed via #5
