### ISSUE TITLE
Flip card memory game 

### ISSUE THREAD

**Issue by mdinesh124** [geekymeeky/JS-games#37]
I would like to add flip card memory game using javascript.

**Comment by mdinesh124** [comment]
Please assign me this to work upon.

**Comment by geekymeeky** [comment]
@mdinesh124 It's already there #32 . Let me know if this will be different, else close this issue

**Comment by mdinesh124** [comment]
It is quite similar but I have an enhanced version of it.
- There will be three levels - casual, medium, hard.
- There will also be a certain time limit.

**Comment by geekymeeky** [comment]
Ok, go for it.
