### ISSUE TITLE
candy crush game

### ISSUE THREAD

**Issue by harshithatnbr** [geekymeeky/JS-games#51]
I want to design a basic candy crush game .
The Tech stacks I use are  HTML, CSS, and JS.
 Please assign me this issue. 
Thankyou.

**Comment by geekymeeky** [comment]
@harshithatnbr Sure. Go ahead

**Comment by geekymeeky** [comment]
@harshithatnbr any update?

**Comment by harshithatnbr** [comment]
Sir I will update you by tomorrow.
