### ISSUE TITLE
Adding new game known as DOT and BOXES

### ISSUE THREAD

**Issue by sumitvajarinkar** [geekymeeky/JS-games#52]
This is a very interesting game. I still play it using pen paper.
If you don't know about this game [click here](https://en.wikipedia.org/wiki/Dots_and_Boxes).
I would like to work on this game, please assign me this under DCP'21.

**Comment by geekymeeky** [comment]
@sumitvajarinkar go ahead

**Comment by geekymeeky** [comment]
@sumitvajarinkar any update?

**Comment by sumitvajarinkar** [comment]
> @sumitvajarinkar any update?

Actually I haven't already prepared game. I'm working on it. I'll push it in upcoming 5 days.
