### ISSUE TITLE
SPACE SHOOTER GAME USING HTML, CSS AND JAVASCRIPT

### ISSUE THREAD

**Issue by pushpakumari5117** [geekymeeky/JS-games#54]
**@geekymeeky 
PLEASE GO THROUGH THIS IDEA ONCE AND ASSIGN IT TO ME UNDER THE DCP21 LABEL, IT WILL BE A GREAT CONTRIBUTION TO YOUR JAVASCRIPT GAMES REPOSITORY.**

**DESCRIPTION :** 
I want to create a SAPCE SHOOTER game using HTML, CSS and JAVASCRIPT.

**FEATURES :**
- CALCULATES SCORE
- HANDLES DIRECTION WITH ARROW KEYS
- IF THE SAVIOUR SPACESHIP COLLIDES  FOR MORE THAN THRICE WITH ALIEN SPACESHIP, THEN GAME FINISHES.
- REPLAY BUTTON WILL BE DISPLAYED WHEN GAME FINISHES
- FINAL SCORE WILL BE DISPLAYED WHEN GAME FINISHES.
- UI WILL BE SIMILAR TO SPACE.

**Comment by geekymeeky** [comment]
@pushpakumari5117 Assigned to you
