### ISSUE TITLE
Enhancement of CONTRIBUTING.MD 

### ISSUE THREAD

**Issue by kanishkaa24** [geekymeeky/JS-games#64]
This is a documentation enhancement issue.
Comment your ideas with relevant references to improve the appearance of the markdown file (eg. Add images, gifs, status, details)
- Issue will be assigned on the basis of your idea and FCFS basis.
- Kindly fill the below template while suggesting the improvement.
- Template
- Add basic guidelines such as CSS and JS files should be updated in static. Project index files should have a navigation etc.

Is your feature request related to a problem? Please describe.

Describe the solution you'd like

Describe alternatives you've considered

Additional context

**Comment by swathi-469** [comment]
I am interested but the issue is to add guidelines to beginners in open source with the resources to be downloaded and git commands .. is that so

**Comment by kanishkaa24** [comment]
> I am interested but the issue is to add guidelines to beginners in open source with the resources to be downloaded and git commands .. is that so

As well as basic guidelines and image support to contribute to this project.
