### ISSUE TITLE
Create Whack-a-mole game

### ISSUE THREAD

**Issue by geekymeeky** [geekymeeky/JS-games#7]
## Aim
- Create Whack A Mole game
## Details
- Few components of the game have already been added.  
- Add new features or improvise the existing features

**Comment by madihamallick** [comment]
@geekymeeky I have added a pull request for this issue. Please review it and let me know if any further changes is to be made.

**Comment by geekymeeky** [comment]
> @geekymeeky I have added a pull request for this issue. Please review it and let me know if any further changes is to be made.

Sure

**Comment by geekymeeky** [comment]
#8
