### ISSUE TITLE
Hang-Man Game

### ISSUE THREAD

**Issue by snehaM2210** [geekymeeky/JS-games#79]
This game is built in Javascript, HTML and CSS and in this game we have to hang the man while guessing the correct word. It also keeps a record of wrong guesses and here when we guess a correct letter the one body part is shown on the hanging rope and one by one body part shows up as we keep on guessing correct letters to the word. It is an interesting game to build and play. If you like the idea, kindly assign me under DCP21.

**Comment by kanishkaa24** [comment]
This game is already a part of the website.
