### ISSUE TITLE
Flip-me game 

### ISSUE THREAD

**Issue by Naman-mahi** [geekymeeky/JS-games#96]
**I want to create a Memory game, please assign me under DCP'21**

**Comment by geekymeeky** [comment]
@Naman-mahi It's already there.

**Comment by Naman-mahi** [comment]
But this game was different

**Comment by geekymeeky** [comment]
@Naman-mahi This can be added as an improvement to the Flip-me game. If that's good with you, I'll reopen the issue.

**Comment by Naman-mahi** [comment]
Okay

**Comment by geekymeeky** [comment]
@Naman-mahi go ahead
